server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuyunsheng93/leyou-config.git
  rabbitmq:
    host: 192.168.0.127
    username: /leyou
    password: leyou
    virtual-host: /leyou


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
