server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 90   #服务失效时间
    lease-renewal-interval-in-seconds: 30  #服务续约时间，默认时间为30秒
spring:
  application:
    name: user-consume-service
  cloud:
     loadbalancer:
      retry:
         enabled: true # 开启Spring Cloud的重试功能
user-service-demo:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1500 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 10 # 切换实例的重试次数
    MaxAutoRetries: 10 # 对当前实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1600